# Sets
sets_from_List = set([13, 49, 15, 30])
print(type(sets_from_List))
print(sets_from_List)
print("---------------------------------------")
s = set()
s.add(1), s.add(1)
s.add(2), s.add(2)
s.add(4)
s.add(5)
s.add(3), s.remove(3)
print(s)
print("---------------------------------------")
s2 = s.union({1, 3, 2, 1, 3, 4, 5})
print(s2)
