# List & List's Functions
Batsman = ["SachinTendulkar", "Virat Kohli",
           "Saurav Ganguly", "Rahul Dravid", "MS Dhoni"]
print(Batsman)
print(Batsman[0])
print(Batsman[1])
print(Batsman[2])
print(Batsman[3])
print(Batsman[4])
print(("-------------------------------------------------------"))
Batsman.append("Mohammad Azharuddin")
Batsman.append("Rohit Sharma")
print(Batsman)
print(("-------------------------------------------------------"))
Batsman.insert(7, "Yuvraj Singh")
print(Batsman)
print(("-------------------------------------------------------"))
Batsman.remove("Rohit Sharma")
print(Batsman)
Batsman.pop()
print(Batsman)
